### PR TITLE
Fix for mingw builds and gcc 7.2 upgrade

### LINKED ISSUE #36: Windows builds are missing libwinpthread-1.dll
As a result, they don't work at all.

```
---------------------------
arm-vita-eabi-gcc-6.2.0.exe - System Error
---------------------------
The program can't start because libwinpthread-1.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

Worked around on msys2 by using mingw64 and installing the `mingw64/mingw-w64-x86_64-libwinpthread-git` package.

### PR DESCRIPTION
**Pull request by codestation**
**feat: copy libwinpthread-1.dll when compiling the windows toolchain**

This will copy libwinpthread-1.dll to vitasdk/bin on windows build. Note that when built with a recent mingw32-w64 compiler, gcc isn't linked to libpthread so this won'tbe necessary when travis upgrades to Ubuntu 16.04. This fixes #36 

**feat: add support for shallow git copies when building the toolchain**

Cmake 3.6 can clone repositories using --depth=1, saving time and bandwidth. This helps to reduce the space and time needed to build the sdk (travis won't benefit from this since their cmake is 3.5.1).

**bump gcc to 7.2.0, binutils to 2.28 and required cmake to 3.2**

* gcc 7.2.0: compiler improvements and better error messages, for example it detects errors on printf overflows.

* binutils 2.29: drop the ugly 2.27 patch

* cmake 3.2: gcc has begun to release lzma tarballs and drop bz2, for example https://ftp.gnu.org/gnu/gcc/gcc-6.4.0/. Cmake 2.8.x doesn't support unpacking xz tarballs. Ubuntu trusty has cmake 3.5.1 on the official repos so the only change to travis script is to add `cmake3` to the package list.

### CODE REVIEW

**Comment by codestation** [comment]
I tested gcc 7.1 by compiling henkaku, taihen, vitashell, and retroarch (for retroarch i compiled all the currently used cores and tested the genesis_gx core).

**Comment by gordon0001** [comment]
yea no problem with gcc7.1. was using a while the snapshots. now i moved to gcc 8 snapshots, binutils always cloned from repo. and compiling homebrew also seems to work very well. indeed they are executable on the system.
my build scripts are for cygwin

moving to 7.1 would be a good step

**Comment by soarqin** [comment]
It is better to build libwinpthread as static library, which gets everything running with trick patches

**Comment by devnoname120** [comment]
@codestation Is it ready for merging?

**Comment by codestation** [comment]
Yes, but requires a merge on vitasdk/autobuilds#4 first so the travis buildscript doesn't break (just an update for cmake, there is one in the official repos).

**Pull request merged**
