### PR TITLE
Build on Pull Requests

### PR DESCRIPTION
**Pull request by frangarcj**

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
@frangarcj it seems upload artifacts in the pull requests. it could change master/release branch only. isn't it?

**Comment by frangarcj** [comment]
I did this to test the pull requests and be able to download a preview of the sdk.

Anyway, artifacts is different from releases. We maybe need to decide if we want to fully remove travis and use something like this for releases.

What's your opinion?

**Comment by d3m3vilurr** [comment]
it contains multiple subjects.

1. migrate github action from travis;
    i'm okay this changes. it might have more option & benefit than travis.

2. uploading artifacts
    i don't like spending data space. pull-request is just request to merge into dev/main stream.
    
    so if someone want to check the (CI) build result, they should do it on the fork repo/local space instead pr.
    (i'm pretty understand your `artifacts are different from releases` meaning.
    yes. i'm worried two things 1. conflict/overwrite release binaries 2. spend space & resources(in this case, time))

**Comment by frangarcj** [comment]
With 1 I'm ok too.

With 2:
I haven't seen limits in resources (space or time) and we are using this approach in Vita3k in order to test the resulting binary locally by the reviewer.

If we add it for master it will be using another step to create a release so no conflict or overwrite

**Comment by d3m3vilurr** [comment]
huh, does github give unlimited storage for team/organization?
i can't believe it. sometimes, they will remove it. (or automatically remove oldest files)
but it's small thing. we can handle it later.

**Comment by frangarcj** [comment]
I think of artifacts as disposable

**Pull request merged**
